# Use a minimal base image (e.g., Alpine Linux) as the base image
FROM alpine:latest

# Set the working directory within the container
WORKDIR /app

# Copy your service's source code into the container
COPY . .

# Specify the command to start your service
CMD ["node", "api.js"]
