version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    build: ./CryptoVisualizationService
    ports:
      - "4001:4001"
    depends_on:
      - rabbitmq
      - crypto-data-service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      
  crypto-data-service:
    build: ../services/crypto-data-service
    ports:
      - "3005:3005"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672

  
