version: '3'
services:
  api:
    build: ./CryptoVisualizationService
    ports:
      - "3006:3006"
  crypto-data-service:
    build: ./services/crypto-data-service
    ports:
      - "3005:3005"
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
